### PR TITLE
Add support for kubeconfig using oidc as AuthProvider

### PR DESCRIPTION
**Pull request by bstick12**
Currently the riff cli will fail with the error message 

`Error: No Auth Provider found for name "oidc"`

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@bstick12 Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=projectriff/riff&pullRequestId=999)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=projectriff/riff&pullRequestId=999) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@bstick12 Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=projectriff/riff&pullRequestId=999)!

**Comment by fbiville** [comment]
Hi @bstick12, thanks for this contribution.
Would you have any suggestion to validate the change?
I'm not sure what the simplest course of action could be here

**Comment by fbiville** [comment]
Ah sorry, I meant a manual test in that case, with a simple enough setup to reproduce the issue you had initially and validate that the change works.

**Comment by jldec** [comment]
This could be validated manually by running on [PKS with UAA integration](https://docs.pivotal.io/runtimes/pks/1-2/installing-pks-gcp.html#uaa).

**Comment by fbiville** [comment]
Merged in b28e9113a7fe1234ad99ec00914a5e2979bae394.
Apologies for the delay, it took me some time to get the proper setup to reproduce this.

**Pull request closed without merging**
