### PR TITLE
Add v0.1.2-rc1 manifest with current versions to the latest release files

### LINKED ISSUE #696: 0.1.2 release - publish and point CLI to latest install yaml for Istio, Knative, eventing, bus
The riff cli depends on published copies of the install yaml for Knative components and for Istio. Currently these are manually prepared and published prior to each release.

Let's please capture how this process is done for others on the team to learn or automate in future.

### PR DESCRIPTION
**Pull request by trisberg**
- files as of 2018-08-29

Resolves #696

### CODE REVIEW

**Comment by scothis** [comment]
LGTM other than the new need to rebase.

**Comment by trisberg** [comment]
Rebased and added a v0.1.2-rc1 so we can test it separately from stable - unless that adds to much complexity for FATS, if so we can make these changes to stable

**Comment by scothis** [comment]
I'd lean towards making this change as stable.
1. FATS will use stable
2. we (riff dev) want to use put a few miles on the build before we release it
3. it needs to end up on stable anyway before we release

**Comment by glyn** [comment]
Rebased and merged as 9926ffef05e841fea63d5d2e6c5e2a7a353b066f.

**Pull request closed without merging**
