### PR TITLE
Clarify riff CLI short option descriptions

### PR DESCRIPTION
**Pull request by dsyer**

### CODE REVIEW

**Comment by ericbottard** [comment]
+1

Waiting for @scothis feedback on one tiny point on his https://github.com/projectriff/riff/pull/394 PR and I'll merge afterwards.

**Comment by scothis** [comment]
The regenerated docs will need to be included in this PR for CI to pass.

**Comment by ericbottard** [comment]
Caught that, I'll do it (unless I forgot :) )

**Comment by ericbottard** [comment]
Merged as 5fb13dbb

**Pull request closed without merging**
