### PR TITLE
Adding Windows batch files for riff, publish and request

### PR DESCRIPTION
**Pull request by trisberg**

### CODE REVIEW

**Comment by dturanski** [comment]
The python sentiments sample fails, the payload arg is not parsed correctly in `publish.bat`
This output when I comment out `@echo off`
----
.\publish tweets "[{\"text\":\"happy happy happy\"},{\"text\":\"sad sad sad\"}]"
 
C:\Users\dtura\Documents\riff-windows>if [happy] == [] (set count=1 )  else (set count=happy )

C:\Users\dtura\Documents\riff-windows>if [happy\"},{\"text\":\"sad] == [] (set pause=0 )  else (set pause=happy\"},{\"text\":\"sad )

C:\Users\dtura\Documents\riff-windows>for /L %i in (1 1 happy) do call :do_post_content tweets [{\"text\":\"happy %i

----

Aside from that, the basic commands I can test from a VM include `riff apply`, `riff delete`, `riff log`, `publish`, `request`  seem to work.

**Comment by trisberg** [comment]
Do you have the real curl command installed?

```
Install Curl: https://skanthak.homepage.t-online.de/download/curl-7.57.0.cab
	Extract
	Add downloaded files to directory and make it part of the path
	Remove existing curl alias using ->  Remove-item alias:curl
```

**Comment by dturanski** [comment]
No, I have a different one

**Comment by trisberg** [comment]
I rebased this on latest master

**Comment by dturanski** [comment]
Merged

**Comment by dturanski** [comment]
As you mentioned, we should add some content for running in Windows. A related issue is that it's not clear from the documentation that you can run with the published sample images, e.g., if you start with `riff apply` , you don't need docker.  You need `curl` at a minimum.  I noticed the windows install behaves differently wrt to `samples/python/sentiments`.  On the mac, either syntax works:
```
 curl -H "Content-Type: text/plain" -X POST http://35.196.105.42:80/messages/tweets -d "[{\"text\":\"happy happy happy\"},{\"text\":\"sad sad sad\"}]"
 curl -H "Content-Type: text/plain" -X POST http://35.196.105.42:80/messages/tweets -d '[{"text":"happy happy happy"},{"text":"sad sad sad"}]'
```
on Windows, the second fails.  And, as mentioned above the `publish` script fails with either.

**Pull request closed without merging**
