### PR TITLE
DNM: Vendor our go dependencies

### PR DESCRIPTION
**Pull request by scothis**
This means our repo is bigger, but builds will no longer be impacted by
network connectivity issues. It should also speed up CI quite a bit.

### CODE REVIEW

**Comment by scothis** [comment]
I'm not sure if this is a good idea, but I wanted to see how CI behaves.

**Comment by scothis** [comment]
By skipping module downloads, we can shave ~90s off each unit test, stage and FATS lite job.

**Comment by glyn** [comment]
Should help local builds too.

**Comment by ericbottard** [comment]
Let's try it!

**Comment by scothis** [comment]
What could go wrong?

**Comment by scothis** [comment]
> What could go wrong?

for starters a silent merge conflict :)

**Pull request merged**
