### PR TITLE
Notify user when a default value for --image is applied

### LINKED ISSUE #1201: Make image name easier to figure out after build
Since #1105 developers can call `function create` without specifying `--image`

Developers should have an easy way to see the actual image name produced from the `--verbose` output of the `function create`, and maybe even from the non-verbose output or perhaps from a variant of `service status` or `service list`.

As a starting point, I suggest adding the image name to the last line of `function create` e.g.

```
riff function create: built image xxxx/xx for service xx. 
```

### PR DESCRIPTION
**Pull request by scothis**
Partially reverts #1204
Replaces #1206
Fixes #1201

### CODE REVIEW

**Comment by ericbottard** [comment]
At least in the case of `--verbose`, the message is printed at the beginning and thus is long gone from the screen when the build finishes, thus defeating the initial purpose of making it clear to the user what the image was

**Comment by scothis** [comment]
Good point. I still think we should say what the default value is when we apply it, this is particularly better for non-verbose/wait uses. How about we also add a message at the end of a verbose command for successful deployments that contains the image that was deployed by the revision?

**Comment by ericbottard** [comment]
Not sure what you mean by "successful" (do you mean sticking that in the if() block for verbose/wait, assuming it exits early on errors?) but yes, I think that is a good option

**Comment by scothis** [comment]
@ericbottard sample outputs indicating the applied --image default (if any) and the deployed image (when waiting).

Normal
```
$ riff function create normal --git-repo https://github.com/projectriff/fats --sub-path functions/uppercase/command
Applied default --image="gcr.io/<snip>/normal"

riff function create completed successfully
Issue `riff service status normal` to see the status of the function
```

With `--wait`
```
$ riff function create wait --wait --git-repo https://github.com/projectriff/fats --sub-path functions/uppercase/command
Applied default --image="gcr.io/<snip>/wait"

riff function create completed successfully
Deployed image "gcr.io/<snip>/wait@sha256:7d74b5177d0212c2668c9430664d944b2824c27c1ff735a1bab941ac9e3927c5"
```

With `--verbose`
```
$ riff function create verbose --verbose --git-repo https://github.com/projectriff/fats --sub-path functions/uppercase/command
Applied default --image="gcr.io/<snip>/verbose"
Waiting for LatestCreatedRevisionName
Waiting on function creation: function creation incomplete: service status unknown: RevisionMissing
<snip>

riff function create completed successfully
Deployed image "gcr.io/<snip>/verbose@sha256:eb312a6c95cbe94a028c15420b0700854bed4de07ddd88dccb35bff915170bf0"
```

With `--dry-run`
```
$ riff function create dry-run --dry-run --git-repo https://github.com/projectriff/fats --sub-path functions/uppercase/command
Applied default --image="gcr.io/<snip>/dry-run"
apiVersion: v1
kind: PersistentVolumeClaim
<snip>
---
apiVersion: serving.knative.dev/v1alpha1
kind: Service
<snip>
---
```

With `--image`
```
$ riff function create image --image gcr.io/<snip>/image --git-repo https://github.com/projectriff/fats --sub-path functions/uppercase/command

riff function create completed successfully
Issue `riff service status image` to see the status of the function
```

With `--wait` and `--image`
```
$ riff function create wait-and-image --wait --image gcr.io/<snip>/wait-and-image --git-repo https://github.com/projectriff/fats --sub-path functions/uppercase/command

riff function create completed successfully
Deployed image "gcr.io/<snip>/wait-and-image@sha256:a4c01a5870b555d8c4c5cf00f2f6f1f302a81c196ec135730b810153d4a0c6c0"
```

**Comment by ericbottard** [comment]
Awesome, best of both worlds!

**Comment by ericbottard** [comment]
Merged as 175a7ccc and parent

**Pull request closed without merging**
