### PR TITLE
For in-cluster builds, use RUN_IMAGE from build template

### PR DESCRIPTION
**Pull request by glyn**
... rather than hard-coded default

Fixes https://github.com/projectriff/riff/issues/1081

### CODE REVIEW

**Comment by ericbottard** [comment]
Isn't that going to break PFS?

**Comment by glyn** [comment]
> Isn't that going to break PFS?

Not really. It would only break PFS if in-cluster builds didn't work with the build template, but then the user could edit the build template `RUN_IMAGE` value rather than attempting to pass a value using an environment variable (which I think should be reserved for local builds).

**Comment by glyn** [comment]
For in-cluster builds, the relocated image value should come from the build template.

**Comment by ericbottard** [comment]
The build template uses a BuildTemplate variable. How does that variable gets its value is my point.
You're saying it will use the default value (after it has been rewritten by relocation)? If so, then it shouldn't be a BuildTemplate parameter at all, don't you agree?

**Comment by glyn** [comment]
Yes. Thanks for filling in a gap in my knowledge.

**Pull request merged**
