### PR TITLE
option --gateway added for publish

### PR DESCRIPTION
**Pull request by ccambien**
option --gateway added for the publish command to specify http-gateway endpoint. 
The property RIFF_GATEWAY has also been added.
This feature is necessary when the http-gateway is accessible through an ingress or a proxy. In this case, the riff cli can't guess the real endpoint by querying the service object in K8s and we need a way to specify the gateway endpoint.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@ccambien Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=projectriff/riff&pullRequestId=616)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=projectriff/riff&pullRequestId=616) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by ericbottard** [comment]
riff now builds on Knative. The new `riff service invoke` command, which basically computes the "gateway" address and provides it to `curl` solves that problem

**Comment by pivotal-issuemaster** [comment]
@ccambien Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=projectriff/riff&pullRequestId=616)!

**Comment by pivotal-issuemaster** [comment]
@ccambien Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=projectriff/riff&pullRequestId=616)!

**Pull request closed without merging**
