### PR TITLE
Normalize backslashes mock paths for Windows

### LINKED ISSUE #1063: `make gen-mocks` fails on Windows
Windows builds are failing when generating mocks. They are able to build when the directory is defined as a relative path, but fail with a fully qualified path. It's very likely a path separator issue as the path uses both back and forward slashes.

```
GO111MODULE=on mockery -output pkg/core/vendor_mocks/mockserving -outpkg mockserving  -dir 	C:\Users\travis\gopath\pkg\mod\github.com\knative\serving@v0.3.0/pkg/client/clientset/versioned                        -name Interface
Unable to find Interface in any go files under this path
```

### PR DESCRIPTION
**Pull request by fbiville**
Fixes #1063

### CODE REVIEW

**Comment by fbiville** [comment]
Though the Windows job seems to stall, the mock generation issue is now fixed (tested locally and on CI).

**Comment by fbiville** [comment]
It seems to me that all mocks are not generated on Windows and the job stalls *afterwards*: https://travis-ci.com/projectriff/riff/jobs/172466636.

**Comment by fbiville** [comment]
Yes, I noticed it locally as well, but the local build succeeds regardless.

**Comment by glyn** [comment]
> Yes, I noticed it locally as well, but the local build succeeds regardless.

[This commit](https://github.com/glyn/riff/commit/8521edd8e3d8efd9d3ba80f9e969ea6571f1c9a4) fixes the problem. Please feel free to include it in this PR.

**Comment by fbiville** [comment]
@glyn Done!

**Pull request merged**
