### PR TITLE
Include riff component version in `riff version`

### PR DESCRIPTION
**Pull request by scothis**
```bash
$ riff version
riff CLI version: 0.0.7-snapshot

COMPONENT             IMAGE
function-controller   projectriff/function-controller:0.0.7-snapshot
http-gateway          projectriff/http-gateway:0.0.7-snapshot
topic-controller      projectriff/topic-controller:0.0.7-snapshot
```

Refs #536

### CODE REVIEW

**Comment by trisberg** [comment]
Very nice. Should we also add the invoker versions currently registered? That could be another PR.

**Comment by scothis** [comment]
@trisberg `riff invokers list` already does that I'm not opposed to duplicating the functionality, but it's redundant.

**Comment by jldec** [comment]
actually i had the same questions as @trisberg - why not include the invokers list
i think there is value in having a single command for users to run to see what's running in their setup.

in addition to the invoker list, i would suggest adding the output of `kc config current-context`
i think it will help for debugging

**Comment by scothis** [comment]
@jldec @trisberg 

now:
```bash
$ riff version
riff CLI version: 0.0.7-snapshot

COMPONENT             IMAGE
function-controller   projectriff/function-controller:0.0.7-snapshot
http-gateway          projectriff/http-gateway:0.0.7-snapshot
topic-controller      projectriff/topic-controller:0.0.7-snapshot

INVOKER   VERSION
java      0.0.6
node      0.0.9-snapshot
```

**Pull request merged**
