### PR TITLE
Improve test coverage

### PR DESCRIPTION
**Pull request by scothis**
- generate more accurate coverage reports

### CODE REVIEW

**Comment by fbiville** [comment]
Hmm, I am not sure I am following. What is the value of empty tests here?

**Comment by sbawaska** [comment]
I'm not sure we need to include the testing package. rest looks good.

**Comment by scothis** [comment]
> Hmm, I am not sure I am following. What is the value of empty tests here?

A package with no tests doesn't contribute towards coverage counts. So the resulting coverage numbers are inflated. Adding empty tests gives a more realistic coverage number. My intent is to push more tests to this PR to raise the overall coverage numbers.

**Comment by fbiville** [comment]
That's quite a strange behavior: it may be worth opening an issue against codecov as well?

**Comment by scothis** [comment]
> That's quite a strange behavior: it may be worth opening an issue against codecov as well?

That seems to be normal for go

**Pull request merged**
