### PR TITLE
Add 2 simple java function examples, fix topics script

### LINKED ISSUE #293: Simple java examples, fix topics script
Add a simple `Flux` function, as well a a simple request/reply function

### PR DESCRIPTION
**Pull request by ericbottard**
Fixes #293

### CODE REVIEW

**Comment by glyn** [comment]
@ericbottard I view of the monrepo proposal, I'd favour moving this PR to its own sample repo.

**Comment by markfisher** [comment]
I think we should consider moving basic samples (e.g. 1 for single-item and 1 for streaming) to the invoker for the samples' language.

**Comment by ericbottard** [comment]
I'll merge this as is and split later. This also fixes the `topics` script

**Comment by ericbottard** [comment]
Merged as 80b4e33

**Pull request closed without merging**
