### PR TITLE
[WIP, DO NOT MERGE] Replace shelling out to cp with go equivalent

### PR DESCRIPTION
**Pull request by glyn**
Fixes https://github.com/projectriff/riff/issues/811
Fixes https://github.com/projectriff/riff/issues/808

### CODE REVIEW

**Comment by glyn** [comment]
Flagging as WIP since this PR is incomplete:
- [ ] inject `fileutils.Utils` into `imageClient`
- [ ] mock `fileutils.Utils` in `pkg/core/image_test.go`
- [ ] convert `fileutils_test.go` to ginkgo/gomega

Flagging as DO NOT MERGE since this PR is stacked on another.

**Comment by ericbottard** [comment]
Overall, LGTM.
I'm not too keen on having something called `*Utils` that is then used in object oriented style (`*Helper` would be slightly better).
Also, I think it would be a bit better to pass a Writer to the constructor instead of a boolean flag for verbosity. One can then pass `/dev/null`, or the actual command `stdout`, or a writer for tests, etc.

So overall, I think this is definitely going into the right direction. The feedback to the user is really good I think (to the extent that we way want to add feeback about rewriting the yaml file, because now it seems only file copying is happening)

**Comment by ericbottard** [comment]
Also, this PR is against a branch that is in the `projectriff` repo. I don't know if that is intended or not. I'm not sure I understand what you mean about all those PRs being stacked on top of one another (please let me know in which order you think it's best we review them)

**Comment by ericbottard** [comment]
Merged as 903ad02c.

Will need to follow up with test conversion to Ginkgo, as well as some additional logging for the whole command (not just the copy part). cc @glyn

**Pull request closed without merging**
