### PR TITLE
Make cli go get'able

### PR DESCRIPTION
**Pull request by scothis**
go get github.com/projectriff/riff

Generally, users should use the released binaries, but having something
that can be installed via `go get` is useful for archetectures we don't
provide releases for, or CI integration.

### CODE REVIEW

**Comment by ericbottard** [comment]
I don't get this. Why not move main.go to the top level directory (of this repo) instead?

**Comment by markfisher** [comment]
I agree `go get github.com/projectriff/riff` would be nicer.

**Comment by scothis** [comment]
moved

**Comment by trisberg** [comment]
Fixed #638

**Pull request merged**
